Add image index
AppFolioOnboarding/image-sharer-aarontcote pull request #10
Opened 2021-03-12 05:34 UTC by aarontcote

Closes #3

2021-03-12 18:00 UTC, Santhanaraman requested changes
I have asked for some minor changes, but overall PR looks great. Thanks!

2021-03-12 18:00 UTC, Santhanaraman commented on test/controllers/images_controller_test.rb
> +    if source_image_count.positive?
Do we need to have this conditional here?

2021-03-12 18:00 UTC, Santhanaraman commented on test/controllers/images_controller_test.rb
> +    assert_equal(source_image_count, page_image_count)
This is very minor: Can we use `assert_equal source_image_count, page_image_count`? What you have is also a valid syntax, its just that with this we can have consistent syntax for all the assertion. What do you think?

2021-03-12 18:00 UTC, Santhanaraman commented on test/controllers/images_controller_test.rb
> +    assert_equal(source_image_count, page_image_count)
Can we also have assertions on the url, and the created at as well, since they both have been added in the view as well?

2021-03-12 18:00 UTC, Santhanaraman commented on app/views/images/new.html.erb
> +</div>
Thanks for updating the other pages as well, and keep them consistent 👍

2021-03-12 18:00 UTC, Santhanaraman commented on app/controllers/images_controller.rb
>    def index
Can we reword the commit message to `Update image index to show newest image first`? This article has been going around the organization a lot that explains how we can write better commit messages  https://chris.beams.io/posts/git-commit/. We haven't made any official announcements around this, but it is being shared across the teams little by little and whoever has got this information are encouraged to enforce it during code review.

2021-03-12 18:00 UTC, Santhanaraman commented on app/views/images/show.html.erb
> +  </div>
Can we add additional test cases for show use case as well, since we have made more updates here?

2021-03-12 18:15 UTC, aarontcote commented on test/controllers/images_controller_test.rb
> +    if source_image_count.positive?
Yes, it'll protect against an assert error (`assert_select 'div.card-body'`) when there are no images present in the table, but as I look at it I'm realizing that the final `assert_equal` is in the wrong location, so I'll get that fixed.

2021-03-12 18:24 UTC, aarontcote reviewed
Yes, I'll update.

2021-03-12 18:57 UTC, aarontcote reviewed
Yes, I can add similar tests as I did on the index page.

2021-03-12 18:57 UTC, aarontcote commented on app/views/images/show.html.erb
> +  </div>
Yes, I can add similar tests as I did on the index page.

2021-03-12 19:00 UTC, aarontcote commented on test/controllers/images_controller_test.rb
> +    if source_image_count.positive?
We don't have any specific requirements for no images, but I'll make an update to the view to show something, and then breakout the test.

2021-03-15 18:42 UTC, Santhanaraman approved these changes

2021-03-15 18:51 UTC, merged