Delete image
AppFolioOnboarding/image-sharer-aarontcote pull request #14
Opened 2021-03-18 17:43 UTC by aarontcote

Closes #7

2021-03-22 19:16 UTC, sarahsehr commented on app/controllers/images_controller.rb
> +    head :not_found
What is the user experience in this case?

2021-03-22 19:17 UTC, sarahsehr commented on test/controllers/images/images_controller_destroy_test.rb
> +    get image_path(created_image.id)
Why do we need a show call in this test?

2021-03-22 19:18 UTC, sarahsehr commented on test/controllers/images/images_controller_destroy_test.rb
> +  test 'delete should not delete image' do
Can we improve the clarity of this test description?

What about `'delete should not delete image for an invalid image id'` or something like that?

2021-03-22 19:27 UTC, sarahsehr commented on test/page_objects/images/image_card.rb
> +        node.find('.card-image')[:src]
In order to avoid the duplicate reference to `.card-image` you can instead do this:

`image.node[:src]`

This will reuse `element :image, locator: '.card-image'`, so that if you change the class name for some reason, you'll only need to change it in one place.

2021-03-22 19:29 UTC, sarahsehr commented on test/page_objects/images/index_page.rb
> +          window.change_to(ShowPage)
I thought, that `windo.change_to` took care of the `stale!`. I need to double check this.

2021-03-22 19:30 UTC, sarahsehr commented on test/page_objects/images/index_page.rb
> +            ((tags.present? && image.tags == tags) || tags.nil?)
Do we need the `||`?

2021-03-22 19:31 UTC, sarahsehr commented on test/page_objects/images/show_page.rb
> +        node.find('.card-image')['src']
Same comment as above.

2021-03-22 19:38 UTC, sarahsehr requested changes
Looks very good. A few comments to address.

2021-03-22 21:49 UTC, aarontcote commented on test/controllers/images/images_controller_destroy_test.rb
> +    get image_path(created_image.id)
I was doing that to verify that it had been created, but that's redundant, so I'll remove.

2021-03-22 21:50 UTC, aarontcote commented on test/controllers/images/images_controller_destroy_test.rb
> +  test 'delete should not delete image' do
Yes, I'll clean it up.

2021-03-22 21:52 UTC, aarontcote commented on test/page_objects/images/image_card.rb
> +        node.find('.card-image')[:src]
Nice, much better, I'll do that.

2021-03-22 22:37 UTC, sarahsehr commented on test/page_objects/images/image_card.rb
> +        node.find('.card-image')[:src]
As we saw in the little diagram that didn't show what I was wanting to convey, each `AePageObjects::Element` is backed by a Capybara `Node`. Calling `node` on the page object element gives us access to that node, so then we can utilize all the Capybara things.

2021-03-22 23:25 UTC, aarontcote commented on test/page_objects/images/index_page.rb
> +            ((tags.present? && image.tags == tags) || tags.nil?)
It looks like `present?` will take care of the check, so I'll remove.

2021-03-22 23:32 UTC, aarontcote commented on test/page_objects/images/index_page.rb
> +            ((tags.present? && image.tags == tags) || tags.nil?)
Cleaned it up to remove the `tags.present?`

2021-03-22 23:47 UTC, aarontcote commented on app/controllers/images_controller.rb
> +    head :not_found
The user will get a 404.

2021-03-23 00:00 UTC, sarahsehr commented on app/controllers/images_controller.rb
> +    head :not_found
I guess that's what Github does. 👍 

In Property we normally give a nice flash message, but I suppose that's not critical.

2021-03-23 00:09 UTC, sarahsehr commented on test/page_objects/images/new_page.rb
> +        stale!
Extra `stale!`

2021-03-23 21:08 UTC, sarahsehr approved these changes

2021-03-23 21:48 UTC, merged