Save image link - Issue #2
AppFolioOnboarding/image-sharer-aarontcote pull request #9
Opened 2021-03-09 21:23 UTC by aarontcote

Closes #2 

---

The following is a checklist to remind you of the steps to take when opening a
new PR. The horizontal line above and everything below can be removed from the
pull request description.

- [ ] I have replaced `X` above with the associated issue number.
- [ ] I have changed the issue's label to "pull request".
- [ ] I have assigned the designated reviewer to this PR.
- [ ] I have set the appropriate label on this PR.
- [ ] I have written clear commit messages ([ref](http://chris.beams.io/posts/git-commit/)).

If needed, please review the document on the
[Image Sharing Project](https://sites.google.com/a/appfolio.com/eng/new-hire-resources/engineering-academy/ropes/image-sharing-project)
for information on how labels should be used.

2021-03-09 23:03 UTC, sarahsehr commented on app/controllers/images_controller.rb
> +end
This symbol means that there isn't a newline at the end of the file. There should be a setting for your text editor to always have a newline at the end of a file.

2021-03-09 23:04 UTC, sarahsehr commented on app/controllers/images_controller.rb
> +end
<img width="871" alt="Screen Shot 2021-03-09 at 3 04 18 PM" src="https://user-images.githubusercontent.com/1709056/110550573-c6bd6100-80e8-11eb-9f87-4a0dd6e63198.png">
This is what it looks like in RubyMine.

2021-03-09 23:07 UTC, sarahsehr commented on app/controllers/images_controller.rb
> +    def image_params
I don't believe it is Ruby style to indent under a `private` or `protected` key word.

2021-03-09 23:09 UTC, sarahsehr commented on app/views/images/new.html.erb
> +<br/>
We should avoid using `br` tags unless they semantically make sense.

Is there another way we can add space between the `h1` and `form` tags?

2021-03-09 23:12 UTC, sarahsehr commented on app/views/images/new.html.erb
> +    <label>Add Your Image URL</label><br>
Does Rails have a way of creating labels?

Can you think of any pros/cons for using the tag directly vs. a Rails helper?

2021-03-09 23:15 UTC, aarontcote commented on app/controllers/images_controller.rb
> +end
Thank you, I've made updates to improve the formatting.

2021-03-09 23:15 UTC, sarahsehr commented on app/views/images/new.html.erb
> +      <div><%= message %></div>
Food for thought, but don't necessarily need to change:

Is `div` the best tag here? Are there other tags that might be better suited for a list?

2021-03-09 23:17 UTC, aarontcote commented on db/migrate/20210309153813_create_images.rb
> +      t.text :url
No, I wouldn't want any image objects without a URL since we aren't uploading the image directly, and I've added validation to ensure the URL is always included.

2021-03-09 23:17 UTC, sarahsehr commented on app/views/images/show.html.erb
> +<%= image_tag(@image.url, alt: 'Image') %>
Is `'Image'` a useful replacement text? Should an image always have an `alt`?

2021-03-09 23:17 UTC, aarontcote commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2021_03_09_153813) do
I'll keep an eye on this going forward.  I ran the migration script after I made the commit, so that's probably where this came from.

2021-03-09 23:18 UTC, sarahsehr commented on app/views/application/home.html.erb
> +<h1>Image URL Uploader</h1>
Is the whole purpose of the website uploading image urls? Or is that more specific to other pages?

2021-03-09 23:20 UTC, aarontcote commented on app/controllers/images_controller.rb
> +    def image_params
I pulled the indenting in from the ROR Getting Started Guide (https://guides.rubyonrails.org/v5.2/getting_started.html), and have now fixed it.

2021-03-09 23:23 UTC, sarahsehr commented on test/controllers/images_controller_test.rb
> + class ImagesControllerTest < ActionDispatch::IntegrationTest
I'm uncertain of what Rails recommends for new projects, but I would expect this test to inherit from `ActionController::TestCase`.

2021-03-09 23:26 UTC, sarahsehr commented on test/controllers/images_controller_test.rb
> +     end
Are there other test cases for this controller? I counted 3 actions and see only 2 tests. Does each action only have one logical path?

2021-03-09 23:27 UTC, sarahsehr commented on db/migrate/20210309153813_create_images.rb
> +      t.text :url
Should there also be checks on the database level?

2021-03-09 23:29 UTC, sarahsehr commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2021_03_09_153813) do
If you'd like we could pair on cleaning up the git history. Otherwise, keeping note of this going forward is fine.

2021-03-09 23:30 UTC, aarontcote commented on app/views/images/new.html.erb
> +    <label>Add Your Image URL</label><br>
Yes, there's the form.label I can use.  I don't see any cons to using it, I'll get it updated.

2021-03-09 23:31 UTC, aarontcote commented on app/views/images/new.html.erb
> +      <div><%= message %></div>
That's a good callout, we could use a ul/li combination here.

2021-03-09 23:31 UTC, sarahsehr requested changes
A very good start!

While not all engineers use Test Drive Development and those that do may not use TDD in all circumstances, I would encourage you to give it a try. :)

2021-03-09 23:32 UTC, aarontcote commented on app/views/images/show.html.erb
> +<%= image_tag(@image.url, alt: 'Image') %>
Doesn't provide a lot of use at this point.  I'll update to use the image id for now, and then it can be supplemented with the tags, or additional description fields later on.

2021-03-09 23:33 UTC, aarontcote commented on app/views/application/home.html.erb
> +<h1>Image URL Uploader</h1>
That's the whole purpose of the site for now.  It looks like I'll replace this page with an Image Index page later on, and then the scope of the site will change.

2021-03-09 23:35 UTC, sarahsehr commented on app/controllers/images_controller.rb
> +    def image_params
Interesting. Good to know. :)

2021-03-09 23:42 UTC, aarontcote commented on test/models/image_test.rb
> +    assert_not image.save
Great question.  Is the valid? operator what we could use here?

2021-03-09 23:43 UTC, sarahsehr commented on test/models/image_test.rb
> +
I think this was resolved already. Closing.

2021-03-09 23:46 UTC, aarontcote commented on app/views/images/new.html.erb
> +<br/>
We could use a div or a p tag, or bring in a CSS library with certain padding values built in, but there are a lot of options here.  I'm definitely open to suggestions on some options you'd like to see.

2021-03-09 23:48 UTC, aarontcote commented on app/views/images/new.html.erb
> +    <label>Add Your Image URL</label><br>
That's great to know. Thank you.

2021-03-09 23:50 UTC, aarontcote commented on test/controllers/images_controller_test.rb
> + class ImagesControllerTest < ActionDispatch::IntegrationTest
Thank you, I'll get it updated.

2021-03-09 23:56 UTC, aarontcote commented on db/migrate/20210309153813_create_images.rb
> +      t.text :url
Good callout, I'll update to set null to false on that column.

2021-03-10 00:00 UTC, aarontcote commented on test/controllers/images_controller_test.rb
> +     end
Since I tested most of the failure cases at the model level, I decided to leave them out at the controller level.  I believe I have an upcoming training on automated testing, but it may be good to get a better idea of the testing approach before then to make sure I match it.

2021-03-10 01:41 UTC, sarahsehr commented on test/models/image_test.rb
> +    assert_not image.save
Yes, `valid?` would be a great choice. What we're testing here really is that the validations work. We know that all the Rails update/save methods call `valid?`

We can also assert that the reason the image is not valid is for the reason we want to me. Otherwise, we might not be testing what we think we are. https://guides.rubyonrails.org/active_record_validations.html#validations-overview-errors can help us verify that.

2021-03-10 01:44 UTC, sarahsehr commented on test/controllers/images_controller_test.rb
> +     assert_response :success
`assert_response :success` will pass for any 2XX value. We prefer our tests to be more specific than that. In this case `assert_response :ok` will assert that the response is exactly 200.

2021-03-10 01:58 UTC, sarahsehr commented on test/controllers/images_controller_test.rb
> +     end
I don't see any test coverage for the new action. I think it deserves at least a response check, but an `assert_select` for the form and input wouldn't hurt.

Ah, you're getting into complicated stuff quickly. :)
So the falsey case of `if @image.save` does not have test coverage. No amount of testing the validations covers that the response is a 422 and the form rerendered.

The question of how to test that is the complicated part. 

The most commonly taken approach is probably to just pick one of the failed validation cases and use that. Since what we're dealing with here is very simple, this is a good approach. You are right that testing all the validation cases would be very redundant (and a waste of time now and on every CI run). 

Another option to consider (but I think is overkill in this case) is contract testing. So you could expect that `@image.save` gets called and have it return false. In this case, it doesn't really matter what the request parameters are. You're just testing that if `save` returns false, X behavior happens. The downside of contract testing is that Ruby doesn't have a way of enforcing that your stub/expectation follows the contract (of Image#save). As a result, it's good to do the contract test (which covers all possible reasons for returning false) as well as one known case that returns false to test the "plumbing" (verifying that you're probably following the contract). This approach is obviously more complex, and I think it's only the right choice if you are dealing with so many cases that utilizing a contract simplifies things.

2021-03-10 17:45 UTC, sarahsehr commented on app/views/images/new.html.erb
> +<br/>
We avoid using tags only for styling. So adding an empty `div` or `p` would have the same problems as a `br`. 

For this project, I'd recommend something simpler. `style="margin-bottom: 1em"`. But yes, in a live app, we'd probably use bootstrap.

2021-03-10 18:58 UTC, aarontcote commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2021_03_09_153813) do
Thank you for going through this.

2021-03-11 00:27 UTC, aarontcote commented on test/controllers/images_controller_test.rb
> + class ImagesControllerTest < ActionDispatch::IntegrationTest
Just an FYI, I tried ActionController::TestCase, and started getting errors, it does look like the new approach is to use ActionDispatch::IntegrationTest for new projects.
https://guides.rubyonrails.org/testing.html#functional-tests-for-your-controllers

2021-03-11 00:37 UTC, sarahsehr commented on test/controllers/images_controller_test.rb
> + class ImagesControllerTest < ActionDispatch::IntegrationTest
Good to know, thank you!

2021-03-11 01:39 UTC, aarontcote commented on test/controllers/images_controller_test.rb
> +     assert_response :success
Updated to check on :ok response.

2021-03-11 01:39 UTC, aarontcote commented on test/controllers/images_controller_test.rb
> +     end
Added checks to the page elements and failed save.

2021-03-11 01:40 UTC, sarahsehr commented on db/migrate/20210310222018_make_urls_non_null_on_images.rb
> +    change_column_null :images, :url, false
I'm unfamiliar with this method. Can you confirm you tried to `bundle exec rake db:rollback` and it successfully undid the change?

2021-03-11 01:42 UTC, aarontcote commented on test/models/image_test.rb
> +    assert_not image.save
Updated to use valid?, and to check for the specific validation check.  I do have concerns about the fragility of tests when you check on a specific string of text in an error message, so let me know if there's a better way to do this in Rails.

2021-03-11 01:42 UTC, aarontcote commented on app/views/images/new.html.erb
> +      <div><%= message %></div>
Updated.

2021-03-11 01:43 UTC, aarontcote commented on app/views/images/new.html.erb
> +    <label>Add Your Image URL</label><br>
Updated.

2021-03-11 01:43 UTC, aarontcote commented on app/views/images/new.html.erb
> +<br/>
Updated.

2021-03-11 01:43 UTC, aarontcote commented on db/migrate/20210309153813_create_images.rb
> +      t.text :url
Updated.

2021-03-11 01:55 UTC, sarahsehr commented on test/controllers/images_controller_test.rb
> +    end
Do we want to assert what the user experience is? What does the response need to include to be a decent user experience?

2021-03-11 02:00 UTC, sarahsehr commented on app/views/application/home.html.erb
> +<div style="float: left; width: 100%; margin-bottom: 2em;">
Curious, is the float and width for other style or did you have trouble adding the margin?

2021-03-11 02:01 UTC, sarahsehr commented on app/views/application/home.html.erb
> +<h1>Image URL Uploader</h1>
We would want to indent the `h1` if it is inside of the `div`.

2021-03-11 02:07 UTC, sarahsehr commented on db/migrate/20210310222018_make_urls_non_null_on_images.rb
> +class MakeUrlsNonNullOnImages < ActiveRecord::Migration[5.2]
Good call on creating a new migration!

A trap people often fall into is to try and edit a migration they already merged. Alternatively, you could have rolled back, edited the migration, and fixed it up into the original migration commit. Nothing wrong with this approach though, it is very clear and iterative. :)

2021-03-11 04:50 UTC, aarontcote commented on db/migrate/20210310222018_make_urls_non_null_on_images.rb
> +    change_column_null :images, :url, false
Yes, I was able to rollback the change, and then re-implement it in the table.

2021-03-11 04:54 UTC, aarontcote commented on app/views/application/home.html.erb
> +<div style="float: left; width: 100%; margin-bottom: 2em;">
No, it worked, but I prefer not to add margin and padding inline in certain tags like h tags.  I usually use something like bootstrap or material UI as my starting css, but In regards to the float and the width, that's just an old habit to make sure divs stack the way I want them too in different browsers when I'm doing it from scratch.

2021-03-11 04:56 UTC, aarontcote commented on app/views/application/home.html.erb
> +<h1>Image URL Uploader</h1>
Yes, definitely, I'll get that updated.  I'm used to it auto formatting for me :)

2021-03-11 05:26 UTC, aarontcote commented on test/controllers/images_controller_test.rb
> +    end
That's a good idea, I've added a check on the error list.

2021-03-11 05:26 UTC, aarontcote commented on app/views/application/home.html.erb
> +<h1>Image URL Uploader</h1>
Updated.

2021-03-11 05:26 UTC, aarontcote commented on db/migrate/20210310222018_make_urls_non_null_on_images.rb
> +class MakeUrlsNonNullOnImages < ActiveRecord::Migration[5.2]
Thank you, that's a good alternative to know about.

2021-03-11 18:05 UTC, sarahsehr commented on app/views/application/home.html.erb
> +<div style="float: left; width: 100%; margin-bottom: 2em;">
> No, it worked, but I prefer not to add margin and padding inline in certain tags like h tags

Hmm, would you mind sharing why? It doesn't matter for this PR, but I am curious. :)

2021-03-11 18:06 UTC, sarahsehr commented on app/views/application/home.html.erb
> +<h1>Image URL Uploader</h1>
Ctrl-Q in Ruby (note ctrl, not cmd) will reformat for you according the to preferences configuration.

2021-03-11 18:09 UTC, sarahsehr commented on test/controllers/images_controller_test.rb
> +    end
I'd also add a `assert_response :unprocessable_entity`

2021-03-11 18:09 UTC, sarahsehr approved these changes
Nice work!

I'd still address that last comment, but I think you can move forward from there.

2021-03-11 18:11 UTC, aarontcote commented on app/views/application/home.html.erb
> +<h1>Image URL Uploader</h1>
Thank you for the tip Sarah.

2021-03-11 18:19 UTC, aarontcote commented on app/views/application/home.html.erb
> +<div style="float: left; width: 100%; margin-bottom: 2em;">
Sure, when I first started doing html and css many years ago, I was trained with the idea of html tags falling into different groups, tags like h and a tags are element tags, so they would include things like font-size and color, and then tags like div and span tags are formatting/arrangement tags, so I still lean towards encapsulating tags within div and span tags to arrange them the way I want.  Now that we use classes on everything, it doesn't matter as much any more, but still something I do when writing out some basic html like this.

2021-03-11 18:26 UTC, aarontcote commented on app/views/images/show.html.erb
> +<%= image_tag(@image.url, alt: 'Image') %>
Based on the alt text article, I've updated the alt tag to be "" until there's more information available.

2021-03-11 18:28 UTC, aarontcote commented on test/controllers/images_controller_test.rb
> +    end
Thank you, I'll add that.

2021-03-11 18:55 UTC, aarontcote commented on test/controllers/images_controller_test.rb
> +    end
I tested this, but it actually returns a 200, not a 422.  Could that be a difference in rails versions, or is the way I have the controller method re-rendering the page incorrect?

2021-03-11 19:11 UTC, sarahsehr commented on test/controllers/images_controller_test.rb
> +    end
My default a `render` calls returns a status of 200. Can you find a way to change it?

2021-03-11 19:18 UTC, aarontcote commented on test/controllers/images_controller_test.rb
> +    end
Yes, I'll update to: `render :new, :status => :unprocessable_entity`

2021-03-11 22:23 UTC, merged